workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    max_build_duration: 120  # <-- Fixed: Maximum allowed is 120 minutes
    instance_type: mac_mini_m2  # Faster M2 machine for quicker pod install & build

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "GrowteqFlowers.xcworkspace"  # Adjust only if ls shows different name
        XCODE_SCHEME: "GrowteqFlowers"

    scripts:
      - name: Clean project (helps avoid stale issues)
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        script: |
          npm install
          cd ios
          # Clean Pods thoroughly
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          # Add modular headers safely (only once)
          if ! grep -q "use_modular_headers!" Podfile; then
            echo "use_modular_headers!" >> Podfile
          fi
          pod install --repo-update
          # Debug: Show ios/ contents
          echo "=== ios/ directory contents after pod install ==="
          ls -la
          # Specific workspace check
          if ls *.xcworkspace >/dev/null 2>&1; then
            echo "Workspace found!"
          else
            echo "ERROR: No .xcworkspace generated! Check Podfile."
            exit 1
          fi
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Build iOS Simulator App
        script: |
          cd ios
          # Clean first
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

          # Build unsigned simulator app
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

          # Debug: Locate the built .app
          echo "=== Built Simulator .app files ==="
          find build -name "*.app" -type d || echo "No .app found - build likely failed earlier"

    artifacts:
      - ios/build/**/*
      - build/**/*
      - build/Build/Products/Release-iphonesimulator/*.app  # Main simulator app bundle
      - ios/*.xcworkspace  # For Podfile debug if needed

    publishing:
      email:
        recipients:
          - manuga262000@gmail.com  # Optional: Get notified on success/failure