workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "GrowteqFlowers.xcworkspace"
        XCODE_SCHEME: "GrowteqFlowers"

    scripts:
      - name: Clean project (helps avoid stale issues)
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        script: |
          npm install
          cd ios
          # Thorough clean
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          # No auto-append needed anymore – use_modular_headers! is in Podfile
          pod install --repo-update
          # Debug output
          echo "=== ios/ directory contents after pod install ==="
          ls -la
          if ls *.xcworkspace >/dev/null 2>&1; then
            echo "Workspace found: $(ls *.xcworkspace)"
          else
            echo "ERROR: No .xcworkspace generated after pod install! Check Podfile syntax."
            exit 1
          fi
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Build iOS Simulator App
        script: |
          cd ios
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            || echo "Clean failed - continuing"

          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

          echo "=== Build finished. Searching for .app bundles ==="
          find . -name "*.app" -type d 2>/dev/null || echo "No .app found in build dir"

          echo "=== Checking DerivedData fallback ==="
          find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d 2>/dev/null || echo "No .app in DerivedData"

    artifacts:
      - ios/build/**/*
      - build/**/*
      - build/Build/Products/Release-iphonesimulator/*.app
      - build/Build/Products/Release-iphonesimulator/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphonesimulator/*.app
      - ios/*.xcworkspace
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - manuga262000@gail.com  # Optional – change to yours