workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "GrowteqFlowers.xcworkspace"
        XCODE_SCHEME: "GrowteqFlowers"

    scripts:
      - name: Clean project (helps avoid stale issues)
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        script: |
          npm install
          cd ios
          rm -rf Pods Podfile.lock build
          pod deintegrate || true
          pod cache clean --all
          pod install --repo-update
          echo "=== ios/ directory contents after pod install ==="
          ls -la
          if ls *.xcworkspace >/dev/null 2>&1; then
            echo "Workspace found: $(ls *.xcworkspace)"
          else
            echo "ERROR: No .xcworkspace! Pod install failed."
            exit 1
          fi
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios

      - name: Build iOS Simulator App
        script: |
          cd ios
          
          # Clean previous builds
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            | xcpretty || true

          # Build for iOS Simulator WITHOUT custom derivedDataPath
          # This ensures CocoaPods modules are found correctly
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            BUILD_DIR=$(pwd)/build/Build/Products \
            OBJROOT=$(pwd)/build/Build/Intermediates.noindex \
            SYMROOT=$(pwd)/build/Build/Products \
            | xcpretty || xcodebuild build \
              -workspace "$XCODE_WORKSPACE" \
              -scheme "$XCODE_SCHEME" \
              -sdk iphonesimulator \
              -configuration Release \
              -destination 'generic/platform=iOS Simulator' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              ONLY_ACTIVE_ARCH=NO \
              BUILD_DIR=$(pwd)/build/Build/Products \
              OBJROOT=$(pwd)/build/Build/Intermediates.noindex \
              SYMROOT=$(pwd)/build/Build/Products

          echo "=== Searching for .app ==="
          find . -name "*.app" -type d 2>/dev/null

          APP_PATH=$(find build -name "*.app" -type d 2>/dev/null | head -1)
          if [ -z "$APP_PATH" ]; then
            # Try default DerivedData location
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "GrowteqFlowers.app" -path "*/Release-iphonesimulator/*" -type d 2>/dev/null | head -1)
          fi
          
          if [ -n "$APP_PATH" ]; then
            echo "Found app at $APP_PATH"
            
            # Verify the app bundle is complete
            if [ -f "$APP_PATH/Info.plist" ]; then
              echo "✅ Info.plist exists!"
              plutil -p "$APP_PATH/Info.plist"
            else
              echo "❌ No Info.plist in .app"
              ls -la "$APP_PATH"
              exit 1
            fi
            
            if [ -f "$APP_PATH/GrowteqFlowers" ]; then
              echo "✅ Executable exists!"
            else
              echo "❌ No executable in .app"
              ls -la "$APP_PATH"
              exit 1
            fi
            
            # Copy to expected location for artifacts
            mkdir -p build/Build/Products/Release-iphonesimulator
            if [ "$APP_PATH" != "build/Build/Products/Release-iphonesimulator/GrowteqFlowers.app" ]; then
              cp -R "$APP_PATH" build/Build/Products/Release-iphonesimulator/
            fi
            
            # Create a zip for Appetize.io
            cd build/Build/Products/Release-iphonesimulator
            zip -r ../../../../GrowteqFlowers-Simulator.zip GrowteqFlowers.app
            cd ../../../../
            echo "✅ Created GrowteqFlowers-Simulator.zip for Appetize.io"
            
          else
            echo "❌ No .app found anywhere"
            echo "Checking DerivedData..."
            find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d 2>/dev/null | head -5
            exit 1
          fi

    artifacts:
      - ios/GrowteqFlowers-Simulator.zip
      - ios/build/Build/Products/Release-iphonesimulator/*.app