workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "GrowteqFlowers.xcworkspace"
        XCODE_SCHEME: "GrowteqFlowers"

    scripts:
      - name: Clean project (helps avoid stale issues)
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        script: |
          npm install
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          if ! grep -q "use_modular_headers!" Podfile; then
            echo "use_modular_headers!" >> Podfile
          fi
          pod install --repo-update
          echo "=== ios/ directory contents after pod install ==="
          ls -la
          if ls *.xcworkspace >/dev/null 2>&1; then
            echo "Workspace found!"
          else
            echo "ERROR: No .xcworkspace generated!"
            exit 1
          fi
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Build iOS Simulator App
        script: |
          cd ios
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 16e,OS=26.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

          echo "=== Built Simulator .app files ==="
          find build -name "*.app" -type d || echo "No .app found"

    artifacts:
      - ios/build/**/*
      - build/**/*
      - build/Build/Products/Release-iphonesimulator/*.app
      - ios/*.xcworkspace