workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "GrowteqFlowers.xcworkspace"
        XCODE_SCHEME: "GrowteqFlowers"

    scripts:
      - name: Clean project (helps avoid stale issues)
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        script: |
          npm install
          cd ios
          rm -rf Pods Podfile.lock build
          pod deintegrate || true
          # Aggressive cache clear for CocoaPods
          rm -rf ~/.cocoapods/repos trunk ~/.cocoapods/cache
          pod cache clean --all
          pod repo update trunk || true
          pod install --repo-update --clean-install
          echo "=== ios/ directory contents after pod install ==="
          ls -la
          if ls *.xcworkspace >/dev/null 2>&1; then
            echo "Workspace found: $(ls *.xcworkspace)"
          else
            echo "ERROR: No .xcworkspace! Pod install failed."
            exit 1
          fi
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Build iOS Simulator App
        script: |
          cd ios
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.0 \
            -derivedDataPath build

          echo "=== Searching for .app ==="
          find . -name "*.app" -type d 2>/dev/null

          APP_PATH=$(find build/Build/Products/Release-iphonesimulator -name "*.app" -type d | head -1)
          if [ -n "$APP_PATH" ]; then
            echo "Found app at $APP_PATH"
            if [ -f "$APP_PATH/Info.plist" ]; then
              echo "Info.plist exists! Contents:"
              plutil -p "$APP_PATH/Info.plist"
            else
              echo "No Info.plist in .app - build incomplete"
            fi
          else
            echo "No .app found"
          fi

    artifacts:
      - ios/build/**/*
      - build/**/*
      - build/Build/Products/Release-iphonesimulator/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphonesimulator/*.app
      - ios/*.xcworkspace