workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120

    environment:
      node: 20
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install --repo-update
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Build iOS Simulator App
        script: |
          cd ios
          # Clean and reinstall Pods to fix any corruption
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          pod install --repo-update

          cd ..

          # Build for simulator (unsigned .app) - no signing flags needed
          xcodebuild build \
            -workspace ios/GrowteqFlowers.xcworkspace \
            -scheme GrowteqFlowers \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

    artifacts:
        - ios/build/**/*
        - build/**/*
