workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120

    environment:
      node: 20
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install || true
          cd ..

      - name: Bundle React Native
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle

      - name: Archive iOS App
        script: |
          xcodebuild -project ios/GrowteqFlowers.xcodeproj \
            -scheme GrowteqFlowers \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ios/build/GrowteqFlowers.xcarchive \
            archive

    artifacts:
      - ios/build/**/*
